stages:
  visualize:
    cmd: python src/visualization.py
    deps:
      - src/visualization.py
      - data/raw/Iris.csv
    outs:
      - reports/pairplot.png
      - reports/heatmap.png
      - reports/histograms.png

  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw/Iris.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train_knn:
    cmd: python src/train_knn.py
    deps:
      - src/train_knn.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
    outs:
      - models/metrics.json

  compare:
    cmd: python src/compare_knn.py
    deps:
      - src/compare_knn.py
      - data/processed/X_test.csv
      - data/processed/y_test.csv
    outs:
      - reports/comparison.txt
